### ISSUE TITLE
(CSU-08) Correção no comportamento do collapsible.

### ISSUE THREAD

**Issue by HugoBex** [UnicariocaDev/Agendador#24]
Caso de Teste Reprovado: 
(CSU-08) Correção no comportamento do collapsible.

Descrição do caso de teste:

**Formulário**

**Descrição:** Esse caso de uso representa o comportamento do formulário todas as vezes em que é clicado.

**Pre-condição: ** Usuário logado

**Pós-condição:** Usuário logado 

Veja mais informações no link:
https://trello.com/c/mzucePtw/20-csu-08-corre%C3%A7%C3%A3o-no-comportamento-do-collapsible

Data última atividade: 
2017-08-26T03:13:34.069Z

Labels:

color: yellow
id: 598ce2de0ab563c4fc771c8d
idBoard: 598ce2de0ab563c4fc771c83
name: Agendar
uses: 17

color: blue
id: 598ce2de0ab563c4fc771c91
idBoard: 598ce2de0ab563c4fc771c83
name: Agendamento
uses: 12

**Comment by yasutot** [comment]
O comportamento padrão do collapsible é fechar somente quando clicado nele novamente.
