### ISSUE TITLE
(CSU-14) Consulta de disciplinas disponíveis

### ISSUE THREAD

**Issue by HugoBex** [UnicariocaDev/Agendador#31]
Caso de Teste Reprovado: 
(CSU-14) Consulta de disciplinas disponíveis

Descrição do caso de teste:

**Consulta de disciplinas disponíveis**

**Descrição:** Este caso de uso representa a análise do comportamento do site quando o usuário desejar consultar quais disciplinas estão disponíveis utilizando o campo "disciplinas" do agendador 

**Pre-condição:** Usuário logado no sistema

**Pós-condição:** Usuário visualiza todas as opções de disciplinas que podem ser agendadas

Veja mais informações no link:
https://trello.com/c/Qgwr7QyM/28-csu-14-consulta-de-disciplinas-dispon%C3%ADveis

Data última atividade: 
2017-09-02T02:43:23.206Z

Labels:

color: blue
id: 598ce2de0ab563c4fc771c91
idBoard: 598ce2de0ab563c4fc771c83
name: Agendamento
uses: 16

color: yellow
id: 598ce2de0ab563c4fc771c8d
idBoard: 598ce2de0ab563c4fc771c83
name: Agendar
uses: 19

**Comment by flaviosc** [comment]
- Bugs corrigidos
