### ISSUE TITLE
(CSU-19) - Consultar unidades e horários

### ISSUE THREAD

**Issue by HugoBex** [UnicariocaDev/Agendador#32]
Caso de Teste Reprovado: 
(CSU-19) - Consultar unidades e horários

Descrição do caso de teste:

**Responsividade**

**Descrição:** O ator utiliza o sistema para consultar quais datas e horários estão disponíveis para agendar sua prova

**Pre-condição:** Usuário logado no sistema.

**Pós-condição:** O Usuário consegue ver todas as unidades e horários disponíveis para cada disciplina 

Veja mais informações no link:
https://trello.com/c/xRVJyv75/33-csu-19-consultar-unidades-e-hor%C3%A1rios

Data última atividade: 
2017-09-02T03:19:07.371Z

Labels:

color: blue
id: 598ce2de0ab563c4fc771c91
idBoard: 598ce2de0ab563c4fc771c83
name: Agendamento
uses: 16

**Comment by yasutot** [comment]
Introdução a programação excluída da lista de unidades de Arquitetura de computação.

Quanto às disciplinas cadastradas com horários iguais, este problema será tratado quando desenvolvermos a tela de edição e criação de novos cadastros.
