### ISSUE TITLE
(CSU-27) Navegação entre páginas de cadastro e agendamento

### ISSUE THREAD

**Issue by HugoBex** [UnicariocaDev/Agendador#36]
Caso de Teste Reprovado: 
(CSU-27) Navegação entre páginas de cadastro e agendamento

Descrição do caso de teste:

**Navegação entre páginas de cadastro e agendamento** 

**Descrição:** Esse caso de uso representa a navegação entre as páginas de cadastro de disciplinas e agendamento de provas através de um botão.

**Pre-condição:** Usuário logado.

**Pós-condição:** Cadastrar disciplina.

Veja mais informações no link:
https://trello.com/c/eF9LbcRE/42-csu-27-navega%C3%A7%C3%A3o-entre-p%C3%A1ginas-de-cadastro-e-agendamento

Data última atividade: 
2017-09-09T01:44:31.134Z

Labels:

color: red
id: 598ce2de0ab563c4fc771c8f
idBoard: 598ce2de0ab563c4fc771c83
name: Cadastro
uses: 12

color: blue
id: 598ce2de0ab563c4fc771c91
idBoard: 598ce2de0ab563c4fc771c83
name: Agendamento
uses: 24

**Comment by LuanPeixotop** [comment]
Corrigido
