### ISSUE TITLE
(CSU-21) Alterações no Componente Tabela

### ISSUE THREAD

**Issue by HugoBex** [UnicariocaDev/Agendador#37]
Caso de Teste Reprovado: 
(CSU-21) Alterações no Componente Tabela

Descrição do caso de teste:

**Alterações no Componente Tabela** 

**Descrição:** Esse caso de uso representa as alterações no componente tabela na qual deverá ser acrescentado os campos Disciplina e Unidade ao cabeçalho, acrescentar os botões de edição e switch para cada registro e recuperar dados das disciplinas agendadas do Firebase (inicialmente será recuperado do arquivo .JSON para testes).

**Pre-condição:** Usuário logado.

**Pós-condição:** Visualizar disciplinas agendadas.

Veja mais informações no link:
https://trello.com/c/dewmotTH/36-csu-21-altera%C3%A7%C3%B5es-no-componente-tabela

Data última atividade: 
2017-09-09T03:05:16.610Z

Labels:

color: red
id: 598ce2de0ab563c4fc771c8f
idBoard: 598ce2de0ab563c4fc771c83
name: Cadastro
uses: 12

color: blue
id: 598ce2de0ab563c4fc771c91
idBoard: 598ce2de0ab563c4fc771c83
name: Agendamento
uses: 24

**Comment by flaviosc** [comment]
- Alterações na tabela feitas e bugs corrigidos
