### ISSUE TITLE
(CSU-28) Checkbox com função para exibir todos os cadastros

### ISSUE THREAD

**Issue by HugoBex** [UnicariocaDev/Agendador#38]
Caso de Teste Reprovado: 
(CSU-28) Checkbox com função para exibir todos os cadastros

Descrição do caso de teste:

**Checkbox com função para exibir todos os cadastros** 

**Descrição:** Esse caso de uso representa a inserção de um checkbox na página de cadastro de disciplinas, que terá a funcionalidade de exibir todos os cadastros realizados ou somente os que estão com o switch "ativo"

**Pre-condição:** Usuário logado.

**Pós-condição:** Visualizar disciplinas cadastradas.

Veja mais informações no link:
https://trello.com/c/SYCkrSbC/43-csu-28-checkbox-com-fun%C3%A7%C3%A3o-para-exibir-todos-os-cadastros

Data última atividade: 
2017-09-12T19:51:11.568Z

Labels:

color: red
id: 598ce2de0ab563c4fc771c8f
idBoard: 598ce2de0ab563c4fc771c83
name: Cadastro
uses: 12

color: blue
id: 598ce2de0ab563c4fc771c91
idBoard: 598ce2de0ab563c4fc771c83
name: Agendamento
uses: 24

**Comment by flaviosc** [comment]
- Funcionamento do switch no Firefox foi corrigido;
 
- Funcionalidade do checkbox corrigida, agora todos os registros são mostrados quando o check está habilitado (incluindo os "desabilitados");

- Mesmo após ser recarregada, a página não torna a mostrar as disciplinas desabilitadas, mostrando somente se o check for selecionado.
